sudo: required
services:
  - docker

before_install:
  - docker build -t nithinvs09/react-test -f ./client/Dockerfile.dev ./client

script: 
  - docker run -e CI=true nithinvs09/react-test npm test

after_success:
  - docker build -t nithinvs09/multi-client ./client
  - docker build -t nithinvs09/multi-nginx ./nginx
  - docker build -t nithinvs09/multi-server ./server
  - docker build -t nithinvs09/multi-worker ./worker

#login to docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  - docker push nithinvs09/multi-client
  - docker push nithinvs09/multi-nginx
  - docker push nithinvs09/multi-server
  - docker push nithinvs09/multi-worker

deploy:
    provider: elasticbeanstalk
    region: 'us-east-1'
    app: 'multi-docker'
    env: 'Multi-docker-env'
    bucker_name: 'elasticbeanstalk-us-east-1-976696653431'
    bucket_path: docker-multi
    on:
      branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY